# Generated by Django 5.2.7 on 2026-02-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_cookhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="expiry_type",
            field=models.CharField(choices=[("use_by", "Use by"), ("best_before", "Best before")], default="best_before", max_length=20),
        ),
    ]

